spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA}
      group-id: group_id      
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#   consumer:
#      bootstrap-servers:  
#      group-id: group_id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      security:
#        protocol: ssl
    producer:
      bootstrap-servers: ${KAFKA}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      host: ${MONGO}
      database: pocvault
      port: 27017